### ISSUE TITLE
Why useridentification can only have 9 digits at most?

### ISSUE THREAD

**Issue by fishfree** [academic-moodle-cooperation/moodle-mod_offlinequiz#122]
In our school, student idnumber includes 10 digits. How to bypass this limit without logic error?

**Comment by univietw** [comment]
The reason lies in the edges of the scans. if the crosses get too close to the edges they are not scanned anymore and by that can't be recognized. If you want you can change the following line in the settingslib.php, line 207 (depending on your version in a different line): 
                if ($digits < 1 || $digits > 9) {

**Comment by fishfree** [comment]
@univietw I edit the code and print a new answer sheet and see why now. Thank you very much! However, I really want 10 digits. Then how to arrange left part within narrower space in order to provide wider right part for 10 digits useridentification?

**Comment by univietw** [comment]
I'm not sure that's gonna be easily possible. The info is spread across the document... The first scanning of the crosses happens in /mod/offlinequiz/report/rimport/scanner.php, line 193:
`                $point = new oq_point(($x * 65) + 1247, ($y * 60) + 306);`
another step is the creation of the pdfs, which happens in pdflib.php, the interesting part for you happens at about line 217:
`$this->Cell($offlinequizconfig->ID_digits * 6.5, 7, '', 1, 1, 'C');  // Box for ID number.`
The problem here is that all of the creation happens relative to the other elements. And without much testing I don't know how to change it, so you're on your own here. :(
The last thing I can imagine creating problems is the file correct.php, where the teachers correct their sheets. I don't think it would need to be changed, but I'm not sure.

**Comment by fishfree** [comment]
@univietw Thank you very much! So I think it would be much better to set a configuralbe setting to adjust the ratio of left part against the right part.
