### ISSUE TITLE
Activity completion with minimal grade.

### ISSUE THREAD

**Issue by Harm01** [academic-moodle-cooperation/moodle-mod_offlinequiz#130]
Hello,
First of all I must say that I am really impressed by this module. I only recently discovered its existence. Until now I used a different solution outside moodle, but your module is far better than that and it makes it possible to include off-line testing in the courses I maintain.

In my courses I make use of the activity completion mechanism in moodle. When a student completes all activities with a minimum grade she/he is granted a certificate. This works with all activities I use, except for your offline quiz.
So my question is:
- is it possible to include a grade to pass option, just like there is in a 'normal' quiz. Like this:
![image](https://user-images.githubusercontent.com/67195868/85204156-c7bc2180-b312-11ea-80bb-3064a0a9d608.png)
- and make it possible to add a require passing grade option to the activity completion. Like thhis:
![image](https://user-images.githubusercontent.com/67195868/85204190-00f49180-b313-11ea-970a-970421bd9408.png)

Hopefully this is not too complicated to implement.
with kind regards,
Harm Lubbers

**Comment by univietw** [comment]
That's a quite nice idea. I've been looking how quiz is doing what you want - sadly it is not THAT simple. We will put it aside for the next release, because we are almost done for Moodle 3.9.
I think it could be done in a day or two. 
If you want to implement it, feel free to make a pull request and I'm happy to merge it, otherwise I'll see for the next release (which will come before moodle 4.0 hopefully)

**Comment by goggo24** [comment]
included in v.3.11.2
