### ISSUE TITLE
Error multiple answers

### ISSUE THREAD

**Issue by LisaE14** [academic-moodle-cooperation/moodle-mod_offlinequiz#131]
My Multiple Choice questions have only one answer. If students tick more answers there should be an error message in the offline quiz.

**Comment by univietw** [comment]
Multiple Choice Questions are exactly for crossing as many answers as the student thinks they are right. 
For your purpose there are single-choice questions.
If students cross more than one answer on those they won't get any points. An error message is not reasonable, because the person seeing the error message is not the person who actually made the error. Which is why we just give them 0 points.
It is possible in the activity settings to set, that students get displayed how many answers are correct.

**Comment by LisaE14** [comment]
Thank you for your fast reply.
