### ISSUE TITLE
Persian and Arabic characters in PDF

### ISSUE THREAD

**Issue by moj101** [academic-moodle-cooperation/moodle-mod_offlinequiz#140]
111 / 5000
Translation results
It is not possible to use Persian or Arabic characters in the output of the Pdf file. Will it be possible to support the feature?

**Comment by univietw** [comment]
Hi Moj,
Thank you for your bug report. At the moment this plugin doesn't get much love, because with corona it's not an often used plugin. I can try how much work it would take to make it work, but it's not a top priority right now.
Probably chinese, japanese, and any other non-latin letters won't work either.

**Comment by moj101** [comment]
hi dear univietw,
Thank you very much for your response
Is it possible to provide technical information about creating a PDF file library and how to use it in your project to see if it is compatible with Unicode?
Thank you again sincerely

**Comment by mwreichel** [comment]
Hi @moj101,
sorry for our late comment - thank you again for reporting this bug.
We will put it in our backlog, but have to do some further investigation on this bug.

As a workaround you could use the DOCX or LATEX format instead, there Arabic and Persion characters should be displayed correctly.

Kind regards,
Martin

**Comment by univietw** [comment]
Hi @moj101
We use the original tcpdf that moodle provides. So we are kind of relying on their Unicode support.
Still, the problem was kind of on our side: Most users at our university wanted a serif less Font, so we used FreeSans as a standard without alternatives. FreeSans sadly does NOT support all kinds of languages (Arabic, Persian, Japanese, Hindu, Korean, ...)
I solved the problem by giving the user the choice to set a font for the pdf.
There will also be an admin setting where you can preselect the pdf font for the whole instance (for new offlinetests).
I set this to freeserif, which is probably fine for most users and it will support Arabic and Persian and most of the languages I mentioned.
You can try it out by checking out the version I pushed to master. Or you wait for the upcoming moodle 4.4 Version somewhere in the next months.
Best regards.
