### ISSUE TITLE
Problem with tiff format

### ISSUE THREAD

**Issue by Gael-Mifsud** [academic-moodle-cooperation/moodle-mod_offlinequiz#17]
Hello,

We have successfully installed the mod on a Moodle 3.1 instance, on Debian Jessie, with PHP 5.6 and ImageMagick.

It works with PNG images, but not with TIFF image.
We have tried 24bits and 1bit (black and white) TIFF format.

It doesn't auto-correct, and when we click on "Correct", a pop-up opens, but in the left of the pop-up we have only a white panel with the icon of a broken file.

I can provide a screenshot or one of the TIFF images, if necessary.

Thank you.

**Comment by mkemmerling** [comment]
Hi Gael,

what file extension do your TIFF images have? There is currently a bug being fixed with '.TIFF' (compared to '.TIF'). Can you confirm that the problem occurs with the three letter extension, too?

Also note that we haven't tested the plugin with Moodle 3.1 thoroughly yet. So feel free to report any other problem that might be related to this Moodle version. We plan to publish a version that has been tested with Moodle 3.1 sometime in September.

Cheers,
Markus

**Comment by Gael-Mifsud** [comment]
Hi Markus,

In fact, it was a misconfiguration in our server.
We had installed php5-imagick, but not imagemagick itself (I frankly thought there was a dependence in between them).
The OfflineQuiz cron log stated that "convert was not found".

After installing ImageMagick, it worked with .TIF images (with only three letter extension) in a zip.


With all our apologies, I will close this false bug report.

Cheers,
Gaël

**Comment by mkemmerling** [comment]
No probs. I am glad to hear that the offline quiz is now working for you.

Cheers,
Markus
