### ISSUE TITLE
Moodle 4.0

### ISSUE THREAD

**Issue by bordonad** [academic-moodle-cooperation/moodle-mod_offlinequiz#174]
Hello,

We thank you for your plugin that our teachers greatly appreciate. I installed it on a Moodle 4.0 and it doesn't work. Have you started adapting your plugin to version 4.0?

Thanking you in advance,

**Comment by fannyny** [comment]
Very good quetion ! We are interested too !

**Comment by tspriet** [comment]
same for us...

**Comment by goggo24** [comment]
We are working on a v.4.0 - but as their a lot of changes with core 4.0 in the are of question bank, we will need some time - please be patient.

**Comment by bordonad** [comment]
Hello,

Thank you for your answer. Without wanting to rush you, do you think that a version for Moodle 4 is possible for the end of September?

Cordially,

**Comment by univietw** [comment]
Just a quick heads up:
I fixed all immediately upcoming issues for moodle 4.0 and it was surprisingly easy. All basic test cases are working. Now this version needs a lot of testing, which will take some weeks.
Once this is done I will publish a version here on github for you guys to work with.
We planned on improving offlinequiz with 4.0 and there might be some edge cases which are always the things that hold back the release of this plugin. Maybe we will release a version 4.0 for immediate usage and release the changes later. But I think I can say that there will be a usable version until end of September, probably some months earlier, depending on what comes up from the testing.

**Comment by carlosrozas** [comment]
Anxiously waiting for offlinequiz for  Moodle 4, good luck guys.

**Comment by rschaufe** [comment]
Is there a chance to get it working before end of July? We would appreciate it so much!

**Comment by univietw** [comment]
I don't know if we are gonna be able to test everything until end of july.

I pushed an alpha version to the master.
This version is not yet tested, I just went through the whole process a couple of times and fixed the immediately upcoming issues. Feel free to use it. I would not recommend the use on a production system.
If you find any errors, please create an issue with the label "moodle_4.0" and I will try to fix it ASAP. I hope this helps a bit

**Comment by univietw** [comment]
I am very sorry we didn't hit the end of july mark. There were a lot of bugs caused by the changes that the questions API did. We also support different question versions now. It is not possible to use the "always latest" option like in the quiz, because it might break the form evaluation. This is a bug that we always wanted to fix, but it was not possible before moodle 4.0.

I have also been working on a new overview page. With this it should be way easier now to understand what to do for new users. This change was needed, because from our tests it seemed our users will not understand the 3rd-level navigation without the tabs. The icons are still subject to change.
There are still some minor things to fix, but it is mainly finished now.
On the upcoming moodle 4.1 release we will modernize the offlinequiz even more.
Any suggestions/errors to this version are highly appreciated.

**Comment by Concombre37** [comment]
Do you have a date or availability for the test on moodle 4.X+?

**Comment by goggo24** [comment]
We are working on the last test cases and bugfixes - we hope to publish it this month.

**Comment by bozdag-ismail** [comment]
Any updates with this? Really interested to see the latest changes you guys have made.

**Comment by goggo24** [comment]
Still struggling with bugs - we're working on it. We hope to have good news soon ... fingercrossed.

**Comment by goggo24** [comment]
v.4.0.0  has been published - have fun!
