### ISSUE TITLE
OfflineQuizz and MimeType

### ISSUE THREAD

**Issue by a-camacho** [academic-moodle-cooperation/moodle-mod_offlinequiz#175]
Hi everyone,

We have some weird issues when uploading large PDF or TIFF files (more than 100 pages).
When we scan these documents with Canon Scanners at our institution, we get .PDF and .TIF files with `MimeType: application/octet-stream`.

If the documents are produced by my Mac OS computer, documents have `MimeType: application/PDF` or `MimeType: image/TIFF`.

- Does this plugin work perfectly with all MimeTypes (octet-stream and PDF/TIFF), or should we be careful about that, and should we be avoiding octet-stream MimeType ?
- Also, does anyone noticed a lesser quality of OCR detection when using TIFF format ?

Finally, could someone provide an example .TIFF file with more than 100 pages that works without any trouble in your Moodle instances ?

Thanks a lot everyone.

**Comment by univietw** [comment]
Hi,

about MIME-Type: I think this will not work, but I am not sure. This MIME-Type stands normally for a runnable program like .exe  You can try uploading it and see if it works, but I think this will not work.
In general we use the mimetype to see the content-Type of a file, the file ending will normally not be taken into consideration.

About your issue with TIFF: It doesn't really matter which format you use for scanning. We recommend to our teachers to scan between 200-300 dpi. All files will be converted to black and white .png anyways so it doesn't matter what type the scan is. We recommend TIF, PNG or PDF to our teachers.

About the questions with very large PDFs and TIFFs, this is probably an issue with the imagemagick not being able to convert these huge files. I would recommend trying to increase your RAM and/or temporary filespace. I would still recommend not uploading such huge PDFs, because moodle moves the file around a couple of times during the upload request.

Hope this helps.
Thomas
