### ISSUE TITLE
Use offlinequiz without registering individuals and answer details

### ISSUE THREAD

**Issue by ncal-4on** [academic-moodle-cooperation/moodle-mod_offlinequiz#176]
Hi there, 

Is there a way to use offline quiz without registering the individuals who are taking the test? Those who are taking the test with paper and pencil will never be logging into Moodle.  We just want to be able to mark the test, keep a record of the marks in the system and be able to export the marks.

Also is there any way to get the details of the marks in the system, say to use for analytics: e.g. what answer was given for question 1 vs the correct answer for the question.

Would appreciate any information and/or suggestion on how I can make the above happen, even if it means a separate tool please let me know.

Thanks

**Comment by goggo24** [comment]
**@tests without registration** - there must be a user in your system so that the offline test result can be connected to. You can also add user manually to your moodle system (also via bulk https://www.youtube.com/watch?v=_kNMOr7Tdw0), so he/she must not login, it's enough when the user is registered in the moodle course.

**@details from answers:** in the tab results you find at the bottom an export option (under the table). There you can downlaod a file with each answer of your students, as well as the correct ones.
![grafik](https://user-images.githubusercontent.com/16721900/170373239-5426d306-4e0f-4f21-be1e-c3655b371fa2.png)

Hope that helps, Eva
