### ISSUE TITLE
Positions of the corner markings

### ISSUE THREAD

**Issue by athasdos** [academic-moodle-cooperation/moodle-mod_offlinequiz#18]
Is it possible to change the default positions of the corner markings? I would really appreciate that you indicate me where I can make this change on the php files. 

Due to different paper sizes;  for instance,  A4 vs US Letter, I think that many people would appreciate  for you to consider the possibility to allow to set different paper sizes

Thanks
![capture](https://cloud.githubusercontent.com/assets/21199299/18286307/bfa30df6-7437-11e6-993b-8ab6fc9c015f.JPG)

**Comment by univietw** [comment]
It's not easy to set the default position, as the position is calculated in a very complex algorithm, where we try to find them by matching. We are rewriting this code at the moment, to make changes at the evaluation of the answer-sheet easier. So in the mid-to-far-future we will support the Letter format as feature.

**Comment by athasdos** [comment]
Thanks for considering to add the Letter format as a feature. I was able to to make it work for me by changing the code on the correct.php file. 

// Define some default corners.
    $corners[0] = new oq_point(95, 67);
    $corners[1] = new oq_point(750, 70);
    $corners[2] = new oq_point(95, 1055);
    $corners[3] = new oq_point(750, 1055);
    $nodbcorners = true;

Thanks for your prompt response and thanks for sharing such as great plugin. 
Sincerely,
Francisco

**Comment by univietw** [comment]
Your change doesn't fix the actual problem and is just a workaround, because it works just for the manual correction after the automated evaluation. So your users will have to open every paper manually and for every non adequately scanned file, they have to adjust the crosses and apply the changes.
Nonetheless thank you for this input, i will show your fix to other people asking for the Letter format as a simple way for using the offlinequiz-plugin with letterformat with some issues. The official support will come in the near future and i will come back to you, if I have any news on this..
