### ISSUE TITLE
Name of the quiz at the top of the answer sheet

### ISSUE THREAD

**Issue by zichichi** [academic-moodle-cooperation/moodle-mod_offlinequiz#180]
would it be possible to enter the name of the quiz in the answer form at the top so as to have it more visible?

**Comment by goggo24** [comment]
At the moment the offline test name is located at the bottom of the answer page. With the plugin itself, there's no way to change the position. But you could edit the pdf before printing => as long as the position of the crosses, boxes and barcodes is not changed (you have to ensure the position because they are all relative), you can change anything within the crosses.

**Comment by goggo24** [comment]
Since it is not a requirement for us, we will not make any changes here and close this issue.
