### ISSUE TITLE
Feaure request: generate course-based IDs

### ISSUE THREAD

**Issue by stdoma** [academic-moodle-cooperation/moodle-mod_offlinequiz#197]
Hello!
I have a suggestion on the topic of ID assignment / student identification.

For various reasons, students may not have stored any numerical IDs in the system.
We are currently not allowed to save the full identification of the students in Moodle (name, e-mail address, matriculation number): data protection and examination regulations

It would be great if you could generate IDs within a course or test so that they can be used. These must be visible to the students so that they can mark them in the test.

You could also store separate IDs in the user profile: when creating the account. These should not be in the user ID field, but in a separate one, so that the field is still available for the correct ID. In the test you should be able to define which ID should be considered.

**Comment by goggo24** [comment]
We don't have this case/requirement at our universites. Therefore we won't change it, because other features are more important for us.  

A note: you can also use the id of the user database table for user identification (thats a numerical field). User can see their IDs, when editing their profile. Or you can use another userfield (e.g. idnumber) and fill it with a unique random number (with same length) via cron/script. This field has to be locked, so that student cannot rewrite it and it can be viewed via the user profile.
