### ISSUE TITLE
Create form error "Exception - Call to undefined method latex::clean_up()"

### ISSUE THREAD

**Issue by agarnav** [academic-moodle-cooperation/moodle-mod_offlinequiz#201]
Hello, I install the plugin today on Moodle 4.1. 
![Create-forms](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2854441/71ce22a8-cce3-46c6-a28e-30ce4d4248b6)

**Comment by agarnav** [comment]
I have a test with question without Latex. It's ok

**Comment by agarnav** [comment]
So, I close this issue. 
This error was due to a bad configuration of latex and/or mimetex

**Comment by agarnav** [comment]
This error was due to a bad configuration of latex and/or mimetex

**Comment by MathieuDomingo** [comment]
Hello,

This issues should be opened, after configuring your mimetex you no longer see the latex error,  because actually latex crash silently and then the code fallback to mimetex.
(By default mimetex crash because the one we get with moodle is not executable, need to chmod 755 moodle/filter/tex/mimetex.linux , or install another one (/usr/bin/mimetex) on the server and configure pathmimetex)


We can see that latex::clean_up() no longer exist , c.f. this commit : https://github.com/moodle/moodle/commit/af7422edc00caa65bba1626495e4b4c10f8906c0
