### ISSUE TITLE
User ID limit

### ISSUE THREAD

**Issue by systems77** [academic-moodle-cooperation/moodle-mod_offlinequiz#213]
Hi
It would be nice if the user ID limit could be extended to 10 digits.

**Comment by univietw** [comment]
You can change it to 10 by editing settingslib.php:207
If I remember correctly we tried it out many years ago to support more digits.
It would be nice if you can try it out first. The problem is, that there isn't enough space. But if you can test it and it still works for you I'd consider testing it again.

**Comment by systems77** [comment]
Hi, thank you for your solution. It was tested and it seems to work with 10 digits. It would be nice if the solution could be implemented and compatible with Moodle 4.1

**Comment by mwreichel** [comment]
This feature was implemented in v.4.3.0.

**Comment by jumabgz** [comment]
Hi, 

could you integrate this fix in the Moodle 4.1 version of offlinequiz.

Regards
