### ISSUE TITLE
anwser form(s) is/are being processed

### ISSUE THREAD

**Issue by opodeur** [academic-moodle-cooperation/moodle-mod_offlinequiz#231]
Hello,
I am testing the plugin with moodle 4.1.6+
I uploaded answer forms and I got this message : "2 answer form(s) is/are being processed ".
Legend icon indicates " Immediate action required".
I don't know what to do, to check.
Is there someone who can help me ?
Regards,
Olivier

**Comment by zichichi** [comment]
In my ubuntu server the problem was due to the fact that it couldn't find "convert" command.
`/opt/plesk/php/8.0/bin/php /var/www/vhosts/xxx.it/xxx.xxx.it//admin/cli/scheduled_task.php --execute="\mod_offlinequiz\task\page_evaluation_task" >> /var/log/moodle/cron.log
**sh: 1: convert: not found`**

I solved it with this command:

sudo apt-get install imagemagick
