### ISSUE TITLE
user_get_participants deprecated methods have been removed and can no longer be used in proivider.php

### ISSUE THREAD

**Issue by taboubi** [academic-moodle-cooperation/moodle-mod_offlinequiz#242]
Since 4.3 The following previously deprecated methods have been removed and can no longer be used:
  - `profile_display_fields`
  - `profile_edit_category`
  - `profile_edit_field`
  - `user_get_participants`
  - `user_get_participants_sql`
  - `user_get_total_participants`
user_get_participants is used in provider.php to get participants in cours.

**Comment by cmichale** [comment]
To Whom It May Concern,
 
 I am out of office until 02 April 2024.

In the meantime please contact
- for questions concerning e-learning including BOKUlearn: ***@***.***
- for questions concerning didactics in higher education: ***@***.***

Best regards,
Claus Rainer Michalek

>>> Issam Taboubi ***@***.***> 14.3.24 22:53 >>>

Since 4.3 The following previously deprecated methods have been removed and can no longer be used:
  - `profile_display_fields`
  - `profile_edit_category`
  - `profile_edit_field`
  - `user_get_participants`
  - `user_get_participants_sql`
  - `user_get_total_participants`
user_get_participants is used in provider.php to get participants in cours.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/242

**Comment by univietw** [comment]
Hi @taboubi,
thank you for your contribution.
You are absolutely right. I have no idea how this could have slipped through.
I will fix it for the next 4.3 release.

**Comment by taboubi** [comment]
Already fixed here https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/commit/c62d5001e8b6ab080c5551ba7b7af3dd9187dcfa

Thank you
