### ISSUE TITLE
Deprecated Creation of dynamic property mod_offlinequiz_display_options::$attempt is deprecated (v4.3.2 2024012202)

### ISSUE THREAD

**Issue by jaume77** [academic-moodle-cooperation/moodle-mod_offlinequiz#252]
Hi,

After upgrading to version v4.3.2 (2024012202), this Warning appears when creating an activity and clicking save. (debug mode activated)

`Deprecated: Creation of dynamic property mod_offlinequiz_display_options::$attempt is deprecated in /var/www/html/moodle432-20240129/mod/offlinequiz/locallib.php on line 1340`

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/db142378-ed09-4a0e-a00b-a5081ce34c64)

Moodle version : 4.3
PHP version : 8.2

Thanks!
Jaume R.

**Comment by univietw** [comment]
Hi @jaume77,
thank you for the issue.
This is an php 8.2 issue (See https://wiki.php.net/rfc/deprecate_dynamic_properties) and already fixed in master and only becomes relevant for PHP 9, which will not be supported by moodle 4.3 anyways, you can just ignore it for the time being.
Since it is just a warning and not displayed to users on production, I didn't bother yet to backport it into 4.3, but if there is going to be a new version I will backport the fixes there too if I have the time.

**Comment by jaume77** [comment]
Ok @univietw !

Thanks!  👍
