### ISSUE TITLE
Custom answers form

### ISSUE THREAD

**Issue by tomaprice** [academic-moodle-cooperation/moodle-mod_offlinequiz#33]
Hi,
I tried to customize answers form. I 'd like to display 100 questions per page with 4 choices (4 box).
I've edited pdflib.php on lines 853 & 854 like that :
$pdf->formtype = 5;
$pdf->colwidth = 7 * 5;

It's ok for the display when I print answers form but it doesn't work when I scan them.
Could you tell me what I need to change please?
Kind regards.
![capture d ecran 2017-02-07 a 16 03 20](https://cloud.githubusercontent.com/assets/22812763/22696632/0a6e84e2-ed4f-11e6-89c7-9a234809e5f1.png)

**Comment by univietw** [comment]
Hi,
looks like you are trying to do one of the undoables, what we have: changing the answer sheets :+1:
The short answer is:
In /report/rimport/scanner.php, it is referenced by the so called variable "formtype" in that class, like the one in the pdflib you found.
The long answer is:
There are some things to bear in mind though:
1. This code is very very old (10 years!). It was written in a time, where moodle didn't have a real API. Expect to get overwhelmed by bare numbers without any explanation and changing them with trial and error. There is no OO-Programming at all in that class and not that much documentation with functions longer than 200 lines full of "if"s and "else"s and "switch" of variables with names that are one character long. This code is no fun at all and you will need to change more than just two lines, I promise you.
2. I think there are some other classes like /correct.php that use this as a reference, but I don't know where, try and find it.
3. There is no chance to have 2 different versions of answer sheet types in one database. The algorithm doesn't work like that and can't decide wether you have 4 or 5 columns by when the answer sheet was printed. So once you changed it, you have to be secure every test that is scanned was printed in the new form, otherwise the results are lost forever. Which is why we can't provide any support for that. You could of course also provide this, but good luck with finding all the dependencies and testing all the conditions, which is nearly impossible.
4. If you really completly understood that code, congratulations, me and my former developer of this plugin didn't. Thats why I am completely rewrite this code at the moment to provide a way to change the form, or change the behavior of how the form is scanned and written into the database in an object orientated way, to change it without any problems. Looks like I'm working on the right spot for you, huh? This will take a while though, as its not first priority and this is not the only project I'm working on, but I will provide some basic code for you, if you are interested.

Anyway, I hope that you find a fast and easy way and you can show me what you changed. I will not provide this feature for the public though, because of the problem I wrote at point 3.

Best regards and Good Luck
Thomas

**Comment by tomaprice** [comment]
Hi,
Thanks a lot for those informations. I'm going to have a look but I'm afraid I'm not good enough in code to deal with those data.  If I find something be sure I'll get back to you!
Best regards.
Thomas

**Comment by tomaprice** [comment]
Hi again,
Could you tell me if/how it's possible to reduce font size and margin between questions on the PDF question to limit number of printed pages?
Best regards.
Thomas

**Comment by univietw** [comment]
hi,

the creation of the questions on the pdf happens in the pdflib.php, around line 550. The margin can be found at multiple places there, depending on if you shuffle your questions.
The fontsize seems to be a configuration of the offlinequiz and should be changeable in the offlinequiz preferences.

**Comment by hsssystems** [comment]
Hi,

how ist the state of rewriting the scan libraries?

br

Harald

**Comment by yusufyilmaz** [comment]
Hello there,

I have enjoyed reading your discussion and have a hope that you can provide more robust solution for different types of forms.

I have been also looking for a solution where we can put 120 answers to one single page. I hope @univietw  has time to provide the new code when it is finished.  

Thank you very much for your effort. We will be contacting again :)

**Comment by univietw** [comment]
I pushed the branch with the actual changes, that I'm working on at the moment: redmine-2768 Nothing works, so it's only to look into the diffs. It'll probably take a while, since I probably need to rewrite more than 50% of the code. support appreciated :D
