### ISSUE TITLE
OfflineQuiz crashing theme

### ISSUE THREAD

**Issue by lbarosi** [academic-moodle-cooperation/moodle-mod_offlinequiz#34]
Hello All,

My setup is: 
Moodle 3.2 
Apache/2.4.18 (Ubuntu) 
Versão do PHP: 7.0.15-0ubuntu0.16.04.4 

As soon as I install offlinequiz plugin the theme crashes and I go back to 1990 web navigation. I tryed original Boost, Roshnilite, Rocket, crisp and waxed themes with the same result. The problem starts when I hit the install button in my moodle, when it comes back with **sucess** it also brings me these problems.

Is there a way to overcome this problem?

**Comment by goggo24** [comment]
The problem is a "}" too much in in styles.css at line #294 - if you delete the sign on your local instance, offline test will work fine with boost. 

In the develop-branch the bugfix is already integrated, but also another feature, that has to be tested first, so we couldn't merge it yet. Please stay patient. Thanks.

**Comment by lbarosi** [comment]
Solution above works fine. Thanks.
