### ISSUE TITLE
Add customization to user identification

### ISSUE THREAD

**Issue by webers-technikum-wien** [academic-moodle-cooperation/moodle-mod_offlinequiz#41]
We have a problem with the current version of Offline Quiz, that renders it unusable in our environment.

While we do have numeric identification for students at our school, the main mode of authentification are alphanumeric student IDs, which also serve as usernames for all our systems including Moodle, and are the only identification I can use inside Moodle.

The letters serve as identification for the study program, so they would always be the same for all users taking a specific exam, however, they would differ between exams if multiple departments are using the Offline Test plugin.

Would it be possible to make the User identification configuration on a per-activity basis instead of only configurable for the whole site by the admin? This way, I could give information to our teachers on how to configure the field for their respective exams, and we could use the plugin at our site.

Alternatively, would it be possible for us to configure the plugin to include certain letters in the matrix for the identification on the answer sheet?

**Comment by univietw** [comment]
Hi, we get the question to use letters quite a lot. It's not that easy to do that, as there is no actual character recognition in the code.
For the user identification per Offlinequiz Instance. I don't think that it's a good idea, because the identification has to be in a column of the users-table, which would imply, that you would get a new user for every offlinequiz, even if they have an account already.

**Comment by webers-technikum-wien** [comment]
_For the user identification per Offlinequiz Instance. I don't think that it's a good idea, because the identification has to be in a column of the users-table, which would imply, that you would get a new user for every offlinequiz, even if they have an account already._

Im sorry, I dont understand what you mean. 

What I meant was: you already have the option of putting fixed letters at fixed positions in the user identification field. You can configure that as an administrator in the general options for the plugin.

If teachers could change which letters are used directly in their quiz, they could configure it in a way that makes it work with their respective course, since the letters for all the users would be the same (we use different letters in our ID codes for different degree programmes, so normally all of the users of a specific course would have the same letters)

example: one course uses IDs iw17b001 to iw17b020 -> i can tell the teacher to configure the quiz so that "IW" and "B" are fixed. another course uses IDs mb17m001 to mb17m020 -> "MB" and "M" would be fixed.

I dont see how that would lead to getting a new user for every offlinequiz, even if an account already exists.

**Comment by univietw** [comment]
Sorry, my answer was not detailed enough to make it understandable. So, this is how the system works:
The plugin searches for a user with a given identification in a certain column in the user table.
Lets say you have configured a[7]=username and the user crosses 1234567, then it would search for a user with following query:
select * from user u where u.username=a1234567
And would write the id of this user into the result table.
Lets say we use your example with an "specialid" field, that you fill through a job:
Quiz A: iw17b[3] = specialid
Quiz B: mb17m[3] = specialid
Then this would lead to conflicts for users who are in both of these tests, because if you want it to work, the user has to have this field set to iw17b001 and mb17m001. (the number in the end doesn't matter in this case)
This would just make sense if you create a new column in the user table or a new user for every offlinetest you are creating, otherwise you would get conflicts.
I think I understood your problem, you want to set a different number for every offlinequiz because your user get an id for every test. Your solution would solve your problem, but the design would create problems for this plugin in the long run, because of this inconsistency.

Don't get me wrong, I really would like to support this feature, because its a valid problem that might help other people as well. Maybe we could find a better solution for temporary IDs, but this has no high priority at the moment.

**Comment by webers-technikum-wien** [comment]
okay, makes sense, i understand now why its not possible from a technical standpoint

thanks for the explanation!
