### ISSUE TITLE
Error while uploading files

### ISSUE THREAD

**Issue by martinvivek** [academic-moodle-cooperation/moodle-mod_offlinequiz#50]
When we upload the answers form we getting this error "Notice: A non well formed numeric value encountered in \mod\offlinequiz\report\rimport\report.php on line 219

When uploading the list it occurs in 
\mod\offlinequiz\participants.php on line 584
 refer screenshot

![image](https://user-images.githubusercontent.com/7712010/32489487-2eaeb666-c3d6-11e7-9721-3851a6554581.png)

moodle version - moodle 3.3.2+ ( 20170915)
offline quiz - version 2017081100
PHP 7.1
windows 2012, IIS 8.5

**Comment by univietw** [comment]
I checked the code of that particular line:
srand(microtime() * 1000000);
For me everything works perfectly fine, but it seems the API changed in php-version 7.1 a little bit.
You can easily delete that line since it only initializes the random number generator, which is done automatically nowadays. Can you tell me if that helps?
If so I will delete it for the next release of moodle 3.4

**Comment by univietw** [comment]
This Problem should be fixed with version 3.4
