### ISSUE TITLE
Add enroll all users button

### ISSUE THREAD

**Issue by fwsl** [academic-moodle-cooperation/moodle-mod_offlinequiz#58]
Hello,

It would be nice to have enroll all(users) button on the import page. 
Currently teacher needs to open each scanned page and click on "Enrol user" button. 

Cheers

**Comment by goggo24** [comment]
Sorry for the late response. The setting was deliberately implemented in this way, because we cannot make sure, that all participants have crossed their _idnumber_ correctly. Therefore the teacher has to check it and can enroll only one student and not all at once. In the worst case a student answer sheet could be associated to a wrong student, if we are doing it automatically. 
At the moment we concentrate on the reorganization of the evaluation algorithm and don't have any resources to take up this idea, so we won't implement it - sorry. Eva
