### ISSUE TITLE
Error "User not in course" 

### ISSUE THREAD

**Issue by lakshmigopal** [academic-moodle-cooperation/moodle-mod_offlinequiz#60]
I am using Moodle version - 2017051503.06 and OfflineQuiz version 2017081102. Getting the error "user not found" when the answer sheet is uploaded though the user is present in the quiz. This is happening only for a few answer sheets uploaded but not all.

**Comment by lakshmigopal** [comment]
![user not in course error](https://user-images.githubusercontent.com/36291396/36019971-ef738b82-0da6-11e8-99d9-d11880eaece4.jpg) p Screenshot of the error.

**Comment by univietw** [comment]
Are you sure the corresponding users are subscribed to your course? Maybe the users don't have a number in the column specified in the admin interface? (See the "Admin Settings" part about user identification in the readme for more info)

**Comment by lakshmigopal** [comment]
@univietw - yes we do have the users subscribed to the course. We could get the results for 18 out of the 25 users. The issue is happening only for a few.  We are getting an error "Page already exists" if we delete the image and re-scan the answer sheet again and upload it.

**Comment by goggo24** [comment]
Is it maybe possible that the number is not unique? We have this problem too when the offline test finds more than one user with the identification number. Can you please check this! 
The second problem could occur because there are partial results in the background. I have only a german screenshot, but i think you will understand it =>select "Show all results" and then sort by column grades, than you can delete the broken results.
![partial_offlinetest](https://user-images.githubusercontent.com/16721900/36143352-272d15aa-10ab-11e8-92e3-375b2039914c.png)
.

**Comment by lakshmigopal** [comment]
@goggo24 , thanks for the inputs. it worked :)

**Comment by goggo24** [comment]
So, did you have 2 users with the same idnumber? Can we close this issue?

**Comment by goggo24** [comment]
Okay, did you try to enrol the user via button "enrol user"? Also the blue boxes in answersheets need attention.

**Comment by lakshmigopal** [comment]
Yes, tried enrol user but nothing happens. All the boxes in answer sheet was also Green.

**Comment by lakshmigopal** [comment]
@goggo24 Do I need to do any setting under participants for allowing the Enrol User button click to work?

**Comment by goggo24** [comment]
Normally, you don't have to change anything, but you can check the capability for your used role : enrol/manual:enrol has to be allowed.  Also you can activate the debugmodus, maybe you get a better errror message when you click on the enrol button. 
If this doesn't help, you can try to enrol the user manually by idnumber under participants and than readjust the answer form & try to save it. When the error appears in our environment, the idnumer is not unique because of old/two accounts. 

Because of cron: it seems to work in your environment, otherwise you wouldn't have results. If you use the cron under scheduled tasks, you only have to set the frequency how often the cron should run - nothing more. If you want to run the cron on a seperate application server, you have to set an additional job.

**Comment by lakshmigopal** [comment]
@goggo24 thanks for the inputs. I checked and all the students are manually enrolled for the course and they have unique ids. There are only about 50 entries and I checked individually that all the ids are unique.   Enabled debug option also but nothing is being shown as error.

**Comment by lakshmigopal** [comment]
@goggo24 Enrol user is working but I am not able to save the data for a particular student.  Do I need to enable any access to the database in Moodle for the offline quiz to write to.

**Comment by goggo24** [comment]
@lakshmigopal:
Hey,  normaly you don't have to change anything on the database. 
I just had the error in a new scenario on our instance. This time the user was already subscrided in the course but by another role than student. As I changed the role, the result could be saved. You could try to unenrol him/her of the course and try to enrol the user only via offline test button.

**Comment by lakshmigopal** [comment]
@goggo24 Thanks for your follow up.  I did what you said, I unenrolled the user. It is allowing me to enrol him through the offline quiz but still not allowing me to save the file.

**Comment by lakshmigopal** [comment]
![untitled](https://user-images.githubusercontent.com/36291396/36930079-0db56b7c-1ec0-11e8-9ddc-bfe3f543a62e.jpg)

**Comment by goggo24** [comment]
Sorry lakshmigopal for not coming back to you. Did you find a solution, can I close the issue?

**Comment by lakshmigopal** [comment]
yes please close the issue. 
    On ‎Friday‎, ‎April‎ ‎5‎, ‎2019‎ ‎02‎:‎46‎:‎04‎ ‎PM‎ ‎IST, Eva Karall <notifications@github.com> wrote:  
 
 
Sorry lakshmigopal for not coming back to you. Did you find a solution, can I close the issue?
