### ISSUE TITLE
Table and field names to creat a CSV output file

### ISSUE THREAD

**Issue by vancouverdeveloper** [academic-moodle-cooperation/moodle-mod_offlinequiz#62]
You plugin was recommend to replace our hard copy version but have some questions:

Current paper test:

1. A test will have multiple questions.

2. Each question is a multiple choice and only one choice is the correct answer.

3. Each question has 5 choices.

4. Each answer choice is represented by a circle. (ie. radio button like)

5. Each choice is associated with a number where choice 1 is "1", choice 2 is "2", choice 3 is "3", choice 4 is "4", choice 5 is "5" (more on this later).

6. The student fills in their answers in an answer sheet by selecting the circle ("radio button") using a pencil like selecting numbers in a lotto form with the associated question.

7. The answer sheet is scanned and the scanner outputs and creates a text file (.CSV) with their student id, name and their answers based on choice number they selected (i.e if they answered a 7 question quiz and all their answers are the 3rd choice the output would be "3333333".

   Example output of .CSV text file:

   Student ID | First Name | Last Name | Answers
   123456789 | John | Smith | 3333333
   987654321 | Mary | Jane | 2351233 
   654753159 | Peter | Parker | 3551421
   etc....

**So my questions are:**

Which tables and column names are involved to query a quiz?

What would the query be to retrieve the answers for each question (does not matter if they are right or wrong) and based on the placement of the question choices? For example in question 1 , they selected the 3rd radio button which means its "3", For question 2, they selected the 1st answer so its a "1", For Question 3, they selected the 4th option (answer), so its a"4".. and so forth?

And how do I tie the quiz with the user and what tables are associated in the union?

Is there a database schema of the tables used in this plugin

**Comment by univietw** [comment]
Hi,

there are a lot of tables involved for what you are looking for.

The algorithm works as following:
1. firstly you have to create groups, which are saved in offlinequiz_groups
2. when you save which questions are part for which group it is saved in offlinequiz_group_questions
3. when you upload a test it saves the sheet(s) in the table offlinequiz_queue
4. the cronjob saves all the information you probably need in these tables:
-offlinequiz_scannedpages (result of the crossed studentid in the column)
-offlinequiz_choices (representation of every box if it is crossed or not)
-offlinequiz_result (id of the templateusage, userid, other information about the result)

if the result is complete, because all answer sheets for the test are done it creates a result with the question-API. I don't know where these are saved, but probably in question, question_answers, question_attempts.

The answer to your second question is the table offlinequiz_choices, but you probably have to think about what to do if the user crossed multiple answers.

the userid is saved in the table offlinequiz_scanned_pages in the column "userkey".

There is no database schema for this plugin, but every table that is used starts with "offlinequiz" and I think the model is quite understandable. If not, feel free to ask :)

**Comment by goggo24** [comment]
@vancouverdeveloper are your question answered and can I close the issue? Cheers, Eva
