### ISSUE TITLE
Error reading from database 

### ISSUE THREAD

**Issue by ron0001** [academic-moodle-cooperation/moodle-mod_offlinequiz#94]
Hi, I tried to upload and correct an offline-quiz and I got different error messages (user not in course, group Error, not adjusted, could not grab and TIFF is not supported - but I used pdf!) by importing the (pdf) file.
If I try to use the „correct“ button, I always receive the following message: „error reading from database“. I have already tried different scanners, as well as various settings, but the result stays the same.

Best regards
Ron

**Comment by goggo24** [comment]
Hey Ron, which version of offline quiz and moodle do you use? Has it ever worked out?

**Comment by webers-technikum-wien** [comment]
we have the exact same issue with moodle 3.6.2 and offline-quiz v3.6.1

- i upload the results of the quiz - 25 are successful, 12 are unsuccessful
- on the upload/correct report page, when I try to click on the "correct" links, i get an "error reading from database" for most of them
- the links that give the db error are for pages that could not be processed due to "could not grab" error and "not adjusted"
- I have two pages with errors "user not in course" and "insecure markings" - those do display normally when opened with the "correct" link

**Comment by webers-technikum-wien** [comment]
more info about the db error with moodle debugging turned on:

it seems like it fails because it could not read the userid correctly?

btw we are using moodle id as identification since we do not have numerical matricle numbers, only alphanumerical


Error reading from database

More information about this error

×Debug info: ERROR: invalid input syntax for integer: "148XX"
SELECT * FROM mdl_user WHERE id = $1
[array (
0 => '148XX',
)]
Error code: dmlreadexception
×Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 859 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1571 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1543 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 636 of /mod/offlinequiz/correct.php: call to moodle_database->get_record()

**Comment by webers-technikum-wien** [comment]
my best guess is that it works for you since you use a different field than moodle user id for identification purposes, and that one does not give a db error when trying to query alphanumerical values.

I got it to work with a few tweaks:

I changed line 636 in correct.php:

`636 if (is_numeric($userkey)) {$user = $DB->get_record('user', array($offlinequizconfig->ID_field => $userkey));} //fix for DB error
`
I also had to evallib.php, otherwise I got the DB error when trying to readjust scanned pages. I added one more if-function starting at line 125:

```
if (is_numeric($scannedpage->userkey)) { //fix for DB error
        $userkey = $scannedpage->userkey;
      } else {
        $userkey = 0;
      }
```
and slightly changed the next line after this one:
`          if (!$user = $DB->get_record('user', array($offlinequizconfig->ID_field => **$userkey**))) {`

**Comment by goggo24** [comment]
Thanks for reporting. We are glad, that you found a workaround for your problem. 
We will include the change in our next major release. Only a question to you:
> and slightly changed the next line after this one:
> if (!$user = $DB->get_record('user', array($offlinequizconfig->ID_field => **$userkey**))) {
... here you only added the if or anything elsse - how can I intreprate **$userkey**?

**Comment by webers-technikum-wien** [comment]
sorry, I shouldnt have added bold to the code, didnt realize that would be turned into ***

to be more clear, the original code, starting from line 124 in evallib.php is:

```
    if ($scannedpage->status == 'ok' || $scannedpage->status == 'suspended') {
        if (!$user = $DB->get_record('user', array($offlinequizconfig->ID_field => $scannedpage->userkey))) {
            $scannedpage->status = 'error';
            $scannedpage->error = 'nonexistinguser';
        } else {
            $coursestudents = get_enrolled_users($coursecontext, 'mod/offlinequiz:attempt');
            if (empty($coursestudents[$user->id])) {
                $scannedpage->status = 'error';
                $scannedpage->error = 'usernotincourse';
            }
        }
    }
```

the problem is, that the variable "$scannedpage->userkey" can be non-numeric if the answer sheet wasnt properly marked or interpreted, eg "123X5".

the get_record then results in a DB-error, since moodle is trying to find a non-numeric user-id

so we first have to change if this value is numeric, and if its not, we just change it into 0 - so the new code, starting from line 124 is:

 ```
   if ($scannedpage->status == 'ok' || $scannedpage->status == 'suspended') {
      if (is_numeric($scannedpage->userkey)) {
        $userkey = $scannedpage->userkey;
      } else {
        $userkey = 0;
      }
      if (!$user = $DB->get_record('user', array($offlinequizconfig->ID_field => $userkey))) {
         $scannedpage->status = 'error';
         $scannedpage->error = 'nonexistinguser';
      } else {
         $coursestudents = get_enrolled_users($coursecontext, 'mod/offlinequiz:attempt');
         if (empty($coursestudents[$user->id])) {
      	    $scannedpage->status = 'error';
            $scannedpage->error = 'usernotincourse';
         }
      }
    }
```

**Comment by goggo24** [comment]
Okay, thanks for clarifying. We will take a look und hopefully find a "nice" solution, which works for everyone.

**Comment by mwreichel** [comment]
Hi @ron0001,

I regret the very late update to your issue.
Since the last message of @goggo24 , much time has passed and we had to rewrite the code in the different areas of the plugin.
In the meantime some rework for the user identification was done too.
Please could you give us feedback, whether the current functions allow you to use it in the way, you were looking for.

All the best,
Martin
