### ISSUE TITLE
question not answered 

### ISSUE THREAD

**Issue by rezzouksamir** [academic-moodle-cooperation/moodle-mod_offlinequiz#97]
Hi 
I am using the Moodle 3.6.2 (Build: 20190114) and the offline quiz v3.6.1. I think there is a bug. some questions are marked as **not answered** with no grade, while the students have indeed answered to those questions with the green square on the scanned answers form. I should mention that the same question is not graded for all the students. It seems that it happens many times randomly. 
Any help would be appreciated thanks

**Comment by goggo24** [comment]
Can you please check if the question is a **multiple choice question** with the setting **"one answer only"**?  
The problem here is, if a student marks MORE than ONE answer, the offline test cannot mark anything, because it's online a single choice question. With single choice questions only one answer is allowed (recognizable by the radiobuttons). So no answer is marked and the student gets 0 points. 
We advise our teachers to use also a multiple choice qustion with "multiple answers allowed" even if there's only one correct answer. Than the problem doesn't appear.

**Comment by rezzouksamir** [comment]
Thank you for your quick answer but it is a multiple choice question. I noticed that if I uncheck manually the green boxes and save the scanned form  and afterwards again I put a green box in the scanned form and I save it, so this time the question is marked properly! 
Thank you for your help

**Comment by goggo24** [comment]
Okay, weird - but than the described behavior should not happen, if it's a multiplechoice question with "more answers allowed". Can I close the issue?
